<?php

namespace Src\App\Models;


use Src\Config\Sql;
use Exception;

class Product extends Model
{
    public static function listAll()
    {
        $sql = new Sql();
        $results = $sql->select('SELECT * FROM tb_products ORDER BY desproduct');
        return $results;

    }
    public function save()
    {
        $sql = new Sql();

        $results = $sql->select('Call sp_products_save(:idproduct, :desproduct, :vlprice, :vlwidth, 
        :vlheight, :vllength, :vlweight, :desurl )',
            array(
            ':idproduct' => $this->getidproduct(),
            ':desproduct' => $this->getdesproduct(),
            ':vlprice'=>$this->getvlprice(),
            ':vlwidth' =>$this->getvlwidth(),
            ':vlheight' =>$this->getvlheight(),
            ':vllength' =>$this->getvllength(),
            ':vlweight' =>$this->getvlweight(),
            ':desurl' =>$this->getdesurl(),
        ));

        $this->setData($results[0]);

    }

    public function get($idProduct)
    {
        $sql = new Sql();

        $results = $sql->select('SELECT * FROM tb_products where idproduct = :idProduct ',array(
            ':idProduct' => $idProduct
        ));

        $this->setData($results[0]);
    }

    public function delete()
    {
        $sql = new Sql();

        $sql->query('DELETE FROM tb_categories WHERE idproduct = :idProduct', array(
            ':idProduct' => $this->getidproduct()
        ));
    }

    public function checkPhoto()
    {
        if(file_exists('/App/view/resource/site/img/products/'.$this->getsetdesphoto()))
        {
            $url =  '/App/view/resource/site/img/products/'.$this->getnamephoto();
        }else
        {
            $url =   '/App/view/resource/site/img/products/product.jpg';
        }

        return $this->setdesphoto($url);
    }

    public function getValues()
    {
        $this->checkPhoto();
        $values =  parent::getValues(); // TODO: Change the autogenerated stub
        return $values;
    }

    public function setPhoto($file)
    {

        $img = explode('/',$file['file']['type']);
        $extension = $img[1];

        switch ($extension)
        {
            case 'jpeg':
                $image = imagecreatefromjpeg($file['file']['tmp_name']);
                break;
            case 'gif':
                $image = imagecreatefromgif($file['file']['tmp_name']);
                break;
            case 'png':
                $image = imagecreatefrompng($file['file']['tmp_name']);
                break;

        }
        var_dump($file['file']['tmp_name']);


        imagejpeg($image,'App/view/resource/site/img/products/');
        imagedestroy($image);
        $this->checkPhoto();

    }


}